apiVersion: apps/v1
kind: Deployment
metadata:
  name: sre-pretest
  labels:
    app: sre-pretest
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sre-pretest
  template:
    metadata:
      labels:
        app: sre-pretest
    spec:
      containers:
      - name: sre-pretest
        image: "${{ DOCKER_USERNAME }}/sre-pretest:latest"
        ports:
        - containerPort: 8080
