name: CI-CD

on:
  push:
    branches: [ "main" ]

jobs:

  terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.12.2

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -var="gcp_credentials=${{secrets.GCP_APIKEY}}"
      
      - name: Download tfstate from artifact
        uses: cloudposse/github-action-terraform-state@v2
        with:
          operation: download
          location: artifact
          directory: .

      - name: Terraform Apply
        run: terraform apply -auto-approve -var="gcp_credentials=${{secrets.GCP_APIKEY}}"
      
      - name: Upload tfstate to artifact
        uses: cloudposse/github-action-terraform-state@v2
        with:
          operation: upload
          location: artifact
          directory: .

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Docker login
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ vars.DOCKER_USERNAME}}/sre-pretest:latest

  deploy:
    runs-on: ubuntu-latest

    needs: [build, terraform]

    steps:
    - uses: actions/checkout@v4
    
    - uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_APIKEY }}'

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: sre-pretest

    - name: Install Helm
      uses: azure/setup-helm@v4

    - name: Test connection
      run: gcloud container clusters list

    - name: Configure GKE Credentials
      run: |
        gcloud container clusters get-credentials "sre-pretest" --project sre-pretest --location ${{ vars.GCP_LOCATION }}
    
    - name: Deploy Helm chart
      run: |
        helm upgrade --install sre-pretest "$GITHUB_WORKSPACE/helm" --set image.repository=${{vars.DOCKER_USERNAME}}/sre-pretest
